### ISSUE TITLE
My First Impression

### ISSUE THREAD

**Issue by Aerwix** [lucasgiovannibr/canaryaac#3]
Hello Devs,

Im testing this new repository and desire this project goes well.

I'd like to say I'm having some troubles with **Uniform Server** and sub pages aren't loading correctly. Even Majesty deleted tutorial for that meanwhile we figure out what just happened.

**I'd like to say a small suggestion**
Since the team always deploy **Local Host Client** with a standard login.php, In other words: http://127.0.0.1/login.php

**CanaryAAC** isn't compatible after installing, so In order to standarize it, why don't change to this one too. I think the project is currenctly using http://127.0.0.1/api/v1/login.php right?

I'd like to this project grow up, so Im here for testing in case needed! 🗡️

**Comment by lucasgiovannibr** [comment]
Thanks.
Yes, little by little I will update and review errors.

There are actually some redirect errors happening, I'm already taking a look at the .htaccess regarding this.

I also thought about changing the login route but for now I'm keeping it the way it is for reasons of keeping track of versions because then it would just change v1 to v2 when you have it.
